- hosts: galaxy
  become: yes
  vars:
#    - galaxy_user:
#        name: galaxy
#    - galaxy_instance_url: http://192.52.33.253
#    - galaxy_config_file_path: "/srv/galaxy/config/galaxy.yml"
#    - galaxy_config_dir: "/srv/galaxy/var/config"
#      galaxy_tools_tool_list_files: [ "files/tool_list.yml" ]
#      galaxy_tools_galaxy_instance_url: "{{ galaxy_instance_url }}"
#      galaxy_tools_api_key: 15a574af28d2d2b6734ca5a20266906c
#      # galaxy_tools_api_key: <API key for Galaxy admin user>
#    - pulsar_jobs_directory: "/data/share/staging/"
#    - message_queue_url : "pyamqp://pulsar_test:password@192.52.34.168:5672//"


  pre_tasks:
    - name: Copy job_conf.xml
      template:
        src: job_conf.xml.j2
        dest: "{{ galaxy_config_dir }}/job_conf.xml"
        owner: "{{ galaxy_user.name }}"
        group: "{{ galaxy_user.name }}"
    - name: Ensure job_config_file exists in the galaxy.yml
      lineinfile:
        path: "{{ galaxy_config_file_path }}"
        line: "    job_config_file: {{ galaxy_config_dir }}/job_conf.xml"
        state: present

  roles:
#    - galaxyprojectdotorg.galaxy-tools
    - galaxyproject.cvmfs
