- hosts: galaxy
  become: yes

  pre_tasks:
    - name: Copy job_conf.xml
      template:
        src: job_conf.xml.j2
        dest: "{{ galaxy_config_dir }}/job_conf.xml"
        owner: "{{ galaxy_user.name }}"
        group: "{{ galaxy_user.name }}"
    - name: Ensure job_config_file exists in the galaxy.yml
      lineinfile:
        path: "{{ galaxy_config_file_path }}"
        line: "    job_config_file: {{ galaxy_config_dir }}/job_conf.xml"
        state: present

#  roles:
#    - galaxyprojectdotorg.galaxy-tools
#    - galaxyproject.cvmfs
